### ISSUE TITLE
Finalize rename from `federation v2` to `kubefed`

### ISSUE THREAD

**Issue by marun** [kubernetes-sigs/kubefed#936]
#860 was only partially completed.  This issue is intended to ensure all remaining instances of 'federation' are removed from the repo before the final beta release.  This is not a strictly mechanical process, and is likely to require rewriting of docs and comments.

TODO:
 - [x] - #938 - Rename cleanup code (pkg, cmd)
 - [x] - #939 - Rename cleanup docs (supercedes #907)
 - [x] - #947 - Rename cleanup tests
 - [x] - #946 - Rename cleanup scripts
 - [x] - #937 - Rename cleanup misc (everything else)
 - [x] - #948 - More misc cleanup to reflect kubefed rename

**Comment by marun** [comment]
@shashidharatd Reference to 'federation' remain in the service dns docs and code.  Do you think it should stay as-is or would it be possible to change as per the discussion of 'federation' -> 'KubeFed control plane' in the WG today?

**Comment by marun** [comment]
All PRs targeted for this issue have merged.
